version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1974
      POSTGRES_DB: users
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: express_app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:1974@db:5432/users
    ports:
      - "3000:3000"
    command: sh -c "npx prisma migrate deploy && node src/index.js"

volumes:
  postgres_data:
